<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $exportCategory = Category::where('slug', 'export')->first();
        $importCategory = Category::where('slug', 'import')->first();

        $products = [
            // ─── EXPORT: COFFEE ────────────────────────────────────────
            [
                'name' => 'Ethiopian Yirgacheffe Coffee Grade 1',
                'slug' => 'ethiopian-yirgacheffe-coffee-grade-1',
                'description' => 'Premium Ethiopian Yirgacheffe Grade 1 coffee beans, renowned for their wine-like acidity, bright citrus notes, and floral aroma. Grown at altitudes above 1,800 meters in the Yirgacheffe region using traditional organic farming methods.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0901.11.00',
                'sku' => 'COFFEE-YIRG-001',
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 1,
                'specifications' => [
                    'grade' => 'Grade 1 (Specialty)',
                    'altitude' => '1,800 – 2,200 m',
                    'processing' => 'Washed (Wet)',
                    'moisture' => '11.5% max',
                    'screen_size' => '14 – 16 mesh',
                    'cup_score' => '85+',
                ],
            ],
            [
                'name' => 'Ethiopian Sidamo Coffee',
                'slug' => 'ethiopian-sidamo-coffee',
                'description' => 'Sidamo coffee offers a rich, full body with vibrant berry and citrus notes. Sourced from the Sidamo highlands, it is one of Ethiopia\'s most sought-after specialty coffees.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0901.11.00',
                'sku' => 'COFFEE-SIDA-002',
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 2,
                'specifications' => [
                    'grade' => 'Grade 2',
                    'altitude' => '1,500 – 2,200 m',
                    'processing' => 'Washed / Natural',
                    'moisture' => '12.0% max',
                    'screen_size' => '14 – 16 mesh',
                ],
            ],
            [
                'name' => 'Ethiopian Harrar Coffee Grade 5',
                'slug' => 'ethiopian-harrar-coffee-grade-5',
                'description' => 'Harrar coffee beans are known for their complex fruity and winey flavors, lower acidity, and rich body. Sourced from the eastern highlands of Ethiopia using traditional dry processing.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0901.11.00',
                'sku' => 'COFFEE-HAR-005',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
                'specifications' => [
                    'grade' => 'Grade 5',
                    'altitude' => '1,400 – 1,800 m',
                    'processing' => 'Natural (Dry)',
                    'moisture' => '12.0% max',
                    'screen_size' => '15 – 18 mesh',
                ],
            ],
            [
                'name' => 'Ethiopian Jimma Coffee',
                'slug' => 'ethiopian-jimma-coffee',
                'description' => 'Jimma coffee delivers a well-balanced cup with mild acidity, medium body, and subtle nutty undertones. A reliable choice for commercial and specialty blends alike.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0901.11.00',
                'sku' => 'COFFEE-JIM-003',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 4,
                'specifications' => [
                    'grade' => 'Grade 3',
                    'altitude' => '1,400 – 1,800 m',
                    'processing' => 'Natural',
                    'moisture' => '12.0% max',
                    'screen_size' => '14 – 16 mesh',
                ],
            ],
            [
                'name' => 'Ethiopian Limu Coffee',
                'slug' => 'ethiopian-limu-coffee',
                'description' => 'Limu coffee is prized for its balanced flavor profile, winey acidity, and pleasant spicy finish. Ideal for espresso blends and single-origin offerings.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0901.11.00',
                'sku' => 'COFFEE-LIM-004',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 5,
                'specifications' => [
                    'grade' => 'Grade 2',
                    'altitude' => '1,500 – 1,900 m',
                    'processing' => 'Washed',
                    'moisture' => '11.5% max',
                    'screen_size' => '14 – 16 mesh',
                ],
            ],
            [
                'name' => 'Ethiopian Ghimbi Coffee',
                'slug' => 'ethiopian-ghimbi-coffee',
                'description' => 'Ghimbi (Lekempti) coffee offers a heavy body with intense fruity and winey notes. It is grown in the western highlands and processed using traditional natural methods.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0901.11.00',
                'sku' => 'COFFEE-GHI-006',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 6,
                'specifications' => [
                    'grade' => 'Grade 2',
                    'altitude' => '1,500 – 2,100 m',
                    'processing' => 'Natural',
                    'moisture' => '12.0% max',
                    'screen_size' => '15 – 17 mesh',
                ],
            ],

            // ─── EXPORT: OILSEEDS ──────────────────────────────────────
            [
                'name' => 'Ethiopian White Sesame Seed',
                'slug' => 'ethiopian-white-sesame-seed',
                'description' => 'High-quality Ethiopian white sesame seeds, ideal for oil production, confectionery, and export. Known for high oil content (48 – 52%), excellent purity, and premium germination rates.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '1207.40.00',
                'sku' => 'SESAME-WHT-001',
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 7,
                'specifications' => [
                    'purity' => '99.95% min',
                    'oil_content' => '48 – 52%',
                    'moisture' => '6.0% max',
                    'ffa' => '1.5% max',
                    'admixture' => '0.05% max',
                ],
            ],
            [
                'name' => 'Ethiopian Niger Seed (Noog)',
                'slug' => 'ethiopian-niger-seed-noog',
                'description' => 'Niger seed (locally known as Noog) is a high-oil-content seed used for human consumption and bird feed. Ethiopia is one of the world\'s largest producers.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '1207.99.00',
                'sku' => 'NOOG-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 8,
                'specifications' => [
                    'purity' => '99.0% min',
                    'oil_content' => '35 – 40%',
                    'moisture' => '8.0% max',
                    'foreign_matter' => '1.0% max',
                ],
            ],
            [
                'name' => 'Ethiopian Soybean',
                'slug' => 'ethiopian-soybean',
                'description' => 'Premium Ethiopian soybeans suitable for oil extraction, animal feed, and food processing. Non-GMO and sourced from smallholder farmers.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '1201.90.00',
                'sku' => 'SOYA-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 9,
                'specifications' => [
                    'protein' => '38 – 42%',
                    'oil_content' => '18 – 20%',
                    'moisture' => '13.0% max',
                    'foreign_matter' => '1.0% max',
                ],
            ],
            [
                'name' => 'Ethiopian Linseed (Flaxseed)',
                'slug' => 'ethiopian-linseed-flaxseed',
                'description' => 'Ethiopian linseed (flaxseed) is rich in omega-3 fatty acids and dietary fiber. Used for oil production, health foods, and industrial applications.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '1204.00.00',
                'sku' => 'LINSEED-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 10,
                'specifications' => [
                    'purity' => '99.0% min',
                    'oil_content' => '35 – 40%',
                    'moisture' => '8.0% max',
                    'foreign_matter' => '1.0% max',
                ],
            ],

            // ─── EXPORT: PULSES ────────────────────────────────────────
            [
                'name' => 'Ethiopian White Kidney Beans',
                'slug' => 'ethiopian-white-kidney-beans',
                'description' => 'Premium quality white kidney beans from Ethiopia, known for their excellent cooking quality, creamy texture, and high protein content. Ideal for canning and retail markets.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0713.33.00',
                'sku' => 'BEANS-WHITE-001',
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 11,
                'specifications' => [
                    'protein' => '22 – 24%',
                    'moisture' => '14.0% max',
                    'foreign_matter' => '1.0% max',
                    'damage' => '2.0% max',
                    'size' => '180 – 200 seeds / 100g',
                ],
            ],
            [
                'name' => 'Ethiopian Red Kidney Beans',
                'slug' => 'ethiopian-red-kidney-beans',
                'description' => 'Vibrant red kidney beans with robust flavor and firm texture. A staple in international cuisine, sourced from Ethiopia\'s highland farming regions.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0713.33.00',
                'sku' => 'BEANS-RED-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 12,
                'specifications' => [
                    'protein' => '22 – 24%',
                    'moisture' => '14.0% max',
                    'foreign_matter' => '1.0% max',
                    'damage' => '2.0% max',
                ],
            ],
            [
                'name' => 'Ethiopian Chickpeas',
                'slug' => 'ethiopian-chickpeas',
                'description' => 'Ethiopian chickpeas (desi and kabuli varieties) are nutrient-dense, high in protein, and widely used in Middle Eastern, Indian, and Mediterranean cuisines.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0713.20.00',
                'sku' => 'CHICKPEA-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 13,
                'specifications' => [
                    'protein' => '20 – 22%',
                    'moisture' => '14.0% max',
                    'foreign_matter' => '1.0% max',
                    'damage' => '2.0% max',
                ],
            ],
            [
                'name' => 'Ethiopian Green Mung Beans',
                'slug' => 'ethiopian-green-mung-beans',
                'description' => 'Green mung beans are small, nutrient-rich legumes popular in Asian cuisine for sprouting, dhal, and dessert production. Cleaned and graded to export standards.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0713.31.00',
                'sku' => 'MUNG-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 14,
                'specifications' => [
                    'purity' => '99.0% min',
                    'moisture' => '13.0% max',
                    'foreign_matter' => '1.0% max',
                    'split_grains' => '2.0% max',
                ],
            ],
            [
                'name' => 'Ethiopian Horse Gram',
                'slug' => 'ethiopian-horse-gram',
                'description' => 'Horse gram is a drought-tolerant legume with high protein and iron content. Used in traditional dishes, animal feed, and ayurvedic applications.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0713.90.00',
                'sku' => 'HORSEGRAM-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 15,
                'specifications' => [
                    'protein' => '22 – 24%',
                    'moisture' => '13.0% max',
                    'foreign_matter' => '1.0% max',
                    'damage' => '2.0% max',
                ],
            ],

            // ─── EXPORT: SPICES ────────────────────────────────────────
            [
                'name' => 'Ethiopian Black Pepper',
                'slug' => 'ethiopian-black-pepper',
                'description' => 'Whole black peppercorns with bold pungency and rich aroma. Ethiopia\'s tropical highlands provide ideal growing conditions for premium pepper.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0904.11.00',
                'sku' => 'PEPPER-BLK-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 16,
                'specifications' => [
                    'piperine' => '4.5 – 6.5%',
                    'moisture' => '12.0% max',
                    'density' => '550 g/L min',
                    'foreign_matter' => '0.5% max',
                ],
            ],
            [
                'name' => 'Ethiopian Ginger',
                'slug' => 'ethiopian-ginger',
                'description' => 'Ethiopian ginger is prized for its high essential oil content, intense flavor, and strong aroma. Available in dried split, powder, and fresh forms.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0910.11.00',
                'sku' => 'GINGER-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 17,
                'specifications' => [
                    'essential_oil' => '2.5 – 4.0%',
                    'moisture' => '10.0% max',
                    'foreign_matter' => '1.0% max',
                    'fibers' => '4.0% max',
                ],
            ],
            [
                'name' => 'Ethiopian Turmeric',
                'slug' => 'ethiopian-turmeric',
                'description' => 'Vibrant Ethiopian turmeric with high curcumin content (3 – 5%). Used in food, cosmetics, and traditional medicine worldwide.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0910.30.00',
                'sku' => 'TURMERIC-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 18,
                'specifications' => [
                    'curcumin' => '3.0 – 5.0%',
                    'moisture' => '10.0% max',
                    'foreign_matter' => '1.0% max',
                    'starch' => '35 – 45%',
                ],
            ],
            [
                'name' => 'Ethiopian Dried Red Chili',
                'slug' => 'ethiopian-dried-red-chili',
                'description' => 'Sun-dried Ethiopian red chilies with intense heat (50,000 – 80,000 SHU) and deep red color. Perfect for spice blends, sauces, and industrial extraction.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0904.22.00',
                'sku' => 'CHILI-RED-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 19,
                'specifications' => [
                    'heat_level' => '50,000 – 80,000 SHU',
                    'moisture' => '10.0% max',
                    'color_astaxanthin' => '120 – 180 ASTA',
                    'foreign_matter' => '1.0% max',
                ],
            ],
            [
                'name' => 'Ethiopian Black Cumin (Nigella)',
                'slug' => 'ethiopian-black-cumin-nigella',
                'description' => 'Black cumin (Nigella sativa) seeds are used as a spice and in traditional medicine. Known for their distinctive peppery flavor and health benefits.',
                'category_id' => $exportCategory?->id,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0910.99.00',
                'sku' => 'CUMIN-BLK-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 20,
                'specifications' => [
                    'purity' => '99.0% min',
                    'moisture' => '10.0% max',
                    'oil_content' => '30 – 35%',
                    'foreign_matter' => '1.0% max',
                ],
            ],

            // ─── IMPORT: AUTOMOTIVE ────────────────────────────────────
            [
                'name' => 'Electric Vehicle (EV)',
                'slug' => 'electric-vehicle-ev',
                'description' => 'Modern electric vehicles (EVs) with zero emissions, advanced battery technology, and smart connectivity. Available in sedan, SUV, and hatchback models from leading manufacturers.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'unit',
                'hs_code' => '8703.80.00',
                'sku' => 'AUTO-EV-001',
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 21,
                'specifications' => [
                    'range' => '400 – 600 km',
                    'battery_capacity' => '60 – 85 kWh',
                    'charging_time' => '30 min (fast charge)',
                    'seating' => '5 passengers',
                ],
            ],
            [
                'name' => 'Hybrid Passenger Car',
                'slug' => 'hybrid-passenger-car',
                'description' => 'Fuel-efficient hybrid cars combining gasoline engines with electric motors. Ideal for urban commuting with reduced fuel consumption and lower emissions.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'unit',
                'hs_code' => '8703.40.00',
                'sku' => 'AUTO-HYB-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 22,
                'specifications' => [
                    'engine' => '1.5L + Electric Motor',
                    'fuel_efficiency' => '20 – 25 km/L',
                    'transmission' => 'CVT / DCT',
                    'seating' => '5 passengers',
                ],
            ],
            [
                'name' => 'Gas-Powered Passenger Car',
                'slug' => 'gas-powered-passenger-car',
                'description' => 'Reliable gasoline-powered passenger cars with modern safety features, comfortable interiors, and proven durability for African road conditions.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'unit',
                'hs_code' => '8703.23.00',
                'sku' => 'AUTO-GAS-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 23,
                'specifications' => [
                    'engine' => '1.6L – 2.0L',
                    'fuel_type' => 'Gasoline',
                    'transmission' => 'Manual / Automatic',
                    'seating' => '5 passengers',
                ],
            ],
            [
                'name' => 'Heavy-Duty Bus',
                'slug' => 'heavy-duty-bus',
                'description' => 'Heavy-duty buses for public transport, intercity travel, and tour operations. Available in 30 – 60 passenger configurations with air conditioning and modern amenities.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'unit',
                'hs_code' => '8702.10.00',
                'sku' => 'AUTO-BUS-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 24,
                'specifications' => [
                    'capacity' => '30 – 60 passengers',
                    'engine' => '6.7L Diesel',
                    'length' => '10.5 – 12.0 m',
                    'features' => 'AC, ABS, Air Suspension',
                ],
            ],

            // ─── IMPORT: CONSTRUCTION MACHINERY ────────────────────────
            [
                'name' => 'Hydraulic Excavator',
                'slug' => 'hydraulic-excavator',
                'description' => 'High-performance hydraulic excavators for mining, earthmoving, and construction projects. Available in 20 – 40 ton classes with advanced hydraulics and fuel efficiency.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'unit',
                'hs_code' => '8429.52.00',
                'sku' => 'MACH-EXC-001',
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 25,
                'specifications' => [
                    'operating_weight' => '20 – 40 t',
                    'bucket_capacity' => '0.9 – 1.5 m³',
                    'engine_power' => '120 – 220 kW',
                    'max_digging_depth' => '6.5 – 7.5 m',
                ],
            ],
            [
                'name' => 'Wheel Loader',
                'slug' => 'wheel-loader',
                'description' => 'Versatile wheel loaders for material handling, loading, and site preparation. Heavy-duty construction with excellent maneuverability and high breakout force.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'unit',
                'hs_code' => '8429.51.00',
                'sku' => 'MACH-LOAD-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 26,
                'specifications' => [
                    'bucket_capacity' => '3.0 – 5.0 m³',
                    'rated_load' => '5,000 – 8,000 kg',
                    'engine_power' => '162 – 220 kW',
                    'dump_height' => '3,100 mm',
                ],
            ],
            [
                'name' => 'Dump Truck',
                'slug' => 'dump-truck',
                'description' => 'Heavy-duty dump trucks for mining, quarry, and large-scale earthmoving operations. Robust chassis and high payload capacity for African conditions.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'unit',
                'hs_code' => '8704.10.00',
                'sku' => 'MACH-DUMP-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 27,
                'specifications' => [
                    'payload' => '30 – 50 t',
                    'engine_power' => '280 – 380 kW',
                    'body_volume' => '16 – 25 m³',
                    'drive' => '6x4 / 8x4',
                ],
            ],
            [
                'name' => 'Motor Grader',
                'slug' => 'motor-grader',
                'description' => 'Precision motor graders for road construction, maintenance, and grading operations. Features articulated frame and advanced blade control systems.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'unit',
                'hs_code' => '8429.20.00',
                'sku' => 'MACH-GRAD-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 28,
                'specifications' => [
                    'blade_width' => '3,660 – 4,270 mm',
                    'engine_power' => '150 – 220 kW',
                    'operating_weight' => '15 – 20 t',
                    'articulation' => '±25°',
                ],
            ],
            [
                'name' => 'Road Roller',
                'slug' => 'road-roller',
                'description' => 'Vibratory and static road rollers for asphalt and soil compaction. Single and double drum configurations with intelligent compaction control.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'unit',
                'hs_code' => '8429.40.00',
                'sku' => 'MACH-ROLL-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 29,
                'specifications' => [
                    'operating_weight' => '10 – 20 t',
                    'engine_power' => '90 – 140 kW',
                    'drum_width' => '2,130 mm',
                    'vibration_frequency' => '28 – 35 Hz',
                ],
            ],
            [
                'name' => 'Bulldozer',
                'slug' => 'bulldozer',
                'description' => 'Powerful crawler bulldozers for heavy earthmoving, land clearing, and mining support. Available with standard and specialized blades.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'unit',
                'hs_code' => '8429.11.00',
                'sku' => 'MACH-BULL-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 30,
                'specifications' => [
                    'operating_weight' => '17 – 35 t',
                    'engine_power' => '130 – 260 kW',
                    'blade_capacity' => '4.5 – 10.0 m³',
                    'ground_pressure' => '50 – 90 kPa',
                ],
            ],
            [
                'name' => 'Concrete Mixer Truck',
                'slug' => 'concrete-mixer-truck',
                'description' => 'Transit concrete mixer trucks with 6 – 12 m³ drum capacity. Heavy-duty chassis ensures reliable concrete delivery for infrastructure projects.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'unit',
                'hs_code' => '8705.40.00',
                'sku' => 'MACH-MIX-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 31,
                'specifications' => [
                    'drum_capacity' => '6 – 12 m³',
                    'engine_power' => '250 – 350 kW',
                    'drive' => '6x4 / 8x4',
                    'discharge_rate' => '≥ 2 m³/min',
                ],
            ],

            // ─── IMPORT: AGRICULTURAL MACHINERY ────────────────────────
            [
                'name' => 'Modern Agricultural Tractor',
                'slug' => 'modern-agricultural-tractor',
                'description' => 'High-performance 4WD agricultural tractors for modern farming. Suitable for plowing, tilling, hauling, and operating implements in Ethiopian agricultural conditions.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'unit',
                'hs_code' => '8701.90.00',
                'sku' => 'AGRI-TRAC-001',
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 32,
                'specifications' => [
                    'engine_power' => '75 – 120 HP',
                    'drive_type' => '4WD',
                    'transmission' => '12F + 12R / 16F + 16R',
                    'pto_speed' => '540 / 1,000 rpm',
                ],
            ],
            [
                'name' => 'Combine Harvester',
                'slug' => 'combine-harvester',
                'description' => 'Self-propelled combine harvesters for wheat, maize, and teff. Efficient threshing, cleaning, and grain handling systems to maximize yield recovery.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'unit',
                'hs_code' => '8433.51.00',
                'sku' => 'AGRI-HARV-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 33,
                'specifications' => [
                    'cutting_width' => '2.5 – 4.0 m',
                    'engine_power' => '100 – 160 HP',
                    'grain_tank' => '3,000 – 5,000 L',
                    'unloading_rate' => '≥ 40 L/s',
                ],
            ],

            // ─── IMPORT: GENERAL IMPORT ────────────────────────────────
            [
                'name' => 'Steel Rebar & Structural Metals',
                'slug' => 'steel-rebar-structural-metals',
                'description' => 'High-tensile steel rebar, angle bars, and structural steel sections for construction and manufacturing. Compliant with international ASTM and BS standards.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'ton',
                'hs_code' => '7214.20.00',
                'sku' => 'GEN-METAL-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 34,
                'specifications' => [
                    'grade' => 'ASTM A615 / BS 4449',
                    'diameter' => '8 – 40 mm',
                    'yield_strength' => '400 – 500 MPa',
                    'length' => '6 – 12 m',
                ],
            ],
            [
                'name' => 'Automotive & Machinery Spare Parts',
                'slug' => 'automotive-machinery-spare-parts',
                'description' => 'Comprehensive range of spare parts for vehicles, construction equipment, and agricultural machinery. OEM and aftermarket parts sourced from certified manufacturers.',
                'category_id' => $importCategory?->id,
                'origin_country' => 'China',
                'unit' => 'unit',
                'hs_code' => '8708.99.00',
                'sku' => 'GEN-SPARE-001',
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 35,
                'specifications' => [
                    'categories' => 'Engine, Transmission, Hydraulics',
                    'warranty' => '6 – 12 months',
                    'quality' => 'OEM / Aftermarket',
                ],
            ],
        ];

        foreach ($products as $data) {
            Product::create($data);
        }
    }
}
