<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // First create some categories if they don't exist
        $categories = [
            ['name' => 'Agricultural Products', 'slug' => 'agricultural-products', 'sort_order' => 1],
            ['name' => 'Textiles', 'slug' => 'textiles', 'sort_order' => 2],
            ['name' => 'Electronics', 'slug' => 'electronics', 'sort_order' => 3],
            ['name' => 'Raw Materials', 'slug' => 'raw-materials', 'sort_order' => 4],
            ['name' => 'Agricultural Equipment', 'slug' => 'agricultural-equipment', 'sort_order' => 5],
            ['name' => 'Food Products', 'slug' => 'food-products', 'sort_order' => 6],
        ];

        foreach ($categories as $category) {
            Category::updateOrCreate(['slug' => $category['slug']], $category);
        }

        // Get category IDs
        $agriCat = Category::where('slug', 'agricultural-products')->first();
        $textileCat = Category::where('slug', 'textiles')->first();
        $electronicsCat = Category::where('slug', 'electronics')->first();
        $materialsCat = Category::where('slug', 'raw-materials')->first();
        $equipmentCat = Category::where('slug', 'agricultural-equipment')->first();
        $foodCat = Category::where('slug', 'food-products')->first();

        $products = [
            [
                'name' => 'Premium Ethiopian Coffee Beans',
                'slug' => 'premium-ethiopian-coffee-beans',
                'sku' => 'COF-001',
                'description' => 'High-quality Ethiopian coffee beans sourced directly from local farmers.',
                'price' => 15.50,
                'cost' => 12.00,
                'quantity' => 1000,
                'category_id' => $agriCat->id ?? null,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0901.11.00',
                'images' => ['coffee1.jpg', 'coffee2.jpg'],
                'specifications' => ['type' => 'Arabica', 'grade' => 'Grade 1', 'moisture' => '11-12%'],
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 1,
            ],
            [
                'name' => 'Organic Sesame Seeds',
                'slug' => 'organic-sesame-seeds',
                'sku' => 'SES-001',
                'description' => 'Premium quality organic sesame seeds for international markets.',
                'price' => 2.80,
                'cost' => 2.20,
                'quantity' => 5000,
                'category_id' => $agriCat->id ?? null,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '1207.40.00',
                'images' => ['sesame1.jpg'],
                'specifications' => ['type' => 'Organic', 'purity' => '99.5%', 'moisture' => '6%'],
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 2,
            ],
            [
                'name' => 'Cotton Fabric',
                'slug' => 'cotton-fabric',
                'sku' => 'TEX-001',
                'description' => 'High-quality cotton fabric for textile manufacturing.',
                'price' => 8.50,
                'cost' => 6.80,
                'quantity' => 2000,
                'category_id' => $textileCat->id ?? null,
                'origin_country' => 'Ethiopia',
                'unit' => 'meter',
                'hs_code' => '5208.11.00',
                'images' => ['cotton1.jpg'],
                'specifications' => ['material' => '100% Cotton', 'width' => '150cm', 'weight' => '200g/m²'],
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
            ],
            [
                'name' => 'Laptop Computers',
                'slug' => 'laptop-computers',
                'sku' => 'ELE-001',
                'description' => 'Imported laptop computers for business and educational use.',
                'price' => 650.00,
                'cost' => 550.00,
                'quantity' => 50,
                'category_id' => $electronicsCat->id ?? null,
                'origin_country' => 'China',
                'unit' => 'piece',
                'hs_code' => '8471.30.00',
                'images' => ['laptop1.jpg'],
                'specifications' => ['processor' => 'Intel i5', 'ram' => '8GB', 'storage' => '256GB SSD'],
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 4,
            ],
            [
                'name' => 'Steel Bars',
                'slug' => 'steel-bars',
                'sku' => 'RAW-001',
                'description' => 'Construction-grade steel bars for building projects.',
                'price' => 650.00,
                'cost' => 580.00,
                'quantity' => 100,
                'category_id' => $materialsCat->id ?? null,
                'origin_country' => 'Ethiopia',
                'unit' => 'ton',
                'hs_code' => '7213.10.00',
                'images' => ['steel1.jpg'],
                'specifications' => ['grade' => 'HRB400', 'diameter' => '12mm', 'length' => '12m'],
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 5,
            ],
            [
                'name' => 'Leather Bags',
                'slug' => 'leather-bags',
                'sku' => 'TEX-002',
                'description' => 'Handcrafted leather bags made from Ethiopian leather.',
                'price' => 45.00,
                'cost' => 35.00,
                'quantity' => 200,
                'category_id' => $textileCat->id ?? null,
                'origin_country' => 'Ethiopia',
                'unit' => 'piece',
                'hs_code' => '4202.21.00',
                'images' => ['bag1.jpg', 'bag2.jpg'],
                'specifications' => ['material' => 'Genuine Leather', 'style' => 'Handbag', 'size' => '30x20x15cm'],
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 6,
            ],
            [
                'name' => 'Spices Mix',
                'slug' => 'spices-mix',
                'sku' => 'FOO-001',
                'description' => 'Traditional Ethiopian spice blend for authentic cuisine.',
                'price' => 12.00,
                'cost' => 9.50,
                'quantity' => 800,
                'category_id' => $agriCat->id ?? null,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0904.11.00',
                'images' => ['spices1.jpg'],
                'specifications' => ['type' => 'Berbere', 'packaging' => '1kg bags', 'shelf_life' => '24 months'],
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 7,
            ],
            [
                'name' => 'Solar Panels',
                'slug' => 'solar-panels',
                'sku' => 'ELE-002',
                'description' => 'High-efficiency solar panels for renewable energy solutions.',
                'price' => 280.00,
                'cost' => 220.00,
                'quantity' => 100,
                'category_id' => $electronicsCat->id ?? null,
                'origin_country' => 'Germany',
                'unit' => 'piece',
                'hs_code' => '8541.41.00',
                'images' => ['solar1.jpg'],
                'specifications' => ['power' => '300W', 'efficiency' => '22%', 'warranty' => '25 years'],
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 8,
            ],
            // Additional Agricultural Products
            [
                'name' => 'Ethiopian White Teff',
                'slug' => 'ethiopian-white-teff',
                'sku' => 'AGR-001',
                'description' => 'Premium quality white teff grain, traditional Ethiopian staple food.',
                'price' => 3.50,
                'cost' => 2.80,
                'quantity' => 2000,
                'category_id' => $agriCat->id ?? null,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '1008.30.00',
                'images' => ['teff1.jpg', 'teff2.jpg'],
                'specifications' => ['type' => 'White Teff', 'purity' => '99%', 'moisture' => '12%'],
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 9,
            ],
            [
                'name' => 'Red Kidney Beans',
                'slug' => 'red-kidney-beans',
                'sku' => 'AGR-002',
                'description' => 'High-quality red kidney beans rich in protein and fiber.',
                'price' => 2.20,
                'cost' => 1.80,
                'quantity' => 3000,
                'category_id' => $agriCat->id ?? null,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0713.33.00',
                'images' => ['beans1.jpg'],
                'specifications' => ['type' => 'Red Kidney', 'moisture' => '14%', 'protein' => '22%'],
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 10,
            ],
            [
                'name' => 'Ethiopian Honey',
                'slug' => 'ethiopian-honey',
                'sku' => 'FOO-002',
                'description' => 'Pure, organic honey from Ethiopian highland flowers.',
                'price' => 18.00,
                'cost' => 14.50,
                'quantity' => 500,
                'category_id' => $foodCat->id ?? null,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0409.00.00',
                'images' => ['honey1.jpg', 'honey2.jpg'],
                'specifications' => ['type' => 'Wild Flower Honey', 'purity' => '100%', 'moisture' => '18%'],
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 11,
            ],
            // Agricultural Equipment
            [
                'name' => 'Tractor John Deere 5045',
                'slug' => 'tractor-john-deere-5045',
                'sku' => 'EQP-001',
                'description' => 'Reliable 45HP tractor suitable for small to medium farms.',
                'price' => 15000.00,
                'cost' => 12000.00,
                'quantity' => 10,
                'category_id' => $equipmentCat->id ?? null,
                'origin_country' => 'USA',
                'unit' => 'piece',
                'hs_code' => '8701.90.00',
                'images' => ['tractor1.jpg', 'tractor2.jpg'],
                'specifications' => ['power' => '45HP', 'engine' => '3-cylinder diesel', 'transmission' => '8F+8R'],
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 12,
            ],
            [
                'name' => 'Irrigation Pump Set',
                'slug' => 'irrigation-pump-set',
                'sku' => 'EQP-002',
                'description' => 'Complete irrigation pump set for agricultural water management.',
                'price' => 850.00,
                'cost' => 680.00,
                'quantity' => 25,
                'category_id' => $equipmentCat->id ?? null,
                'origin_country' => 'China',
                'unit' => 'set',
                'hs_code' => '8413.60.00',
                'images' => ['pump1.jpg'],
                'specifications' => ['flow_rate' => '30 m³/h', 'power' => '7.5 HP', 'head' => '45m'],
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 13,
            ],
            [
                'name' => 'Thresher Machine',
                'slug' => 'thresher-machine',
                'sku' => 'EQP-003',
                'description' => 'Multi-crop thresher machine for efficient grain processing.',
                'price' => 2200.00,
                'cost' => 1800.00,
                'quantity' => 15,
                'category_id' => $equipmentCat->id ?? null,
                'origin_country' => 'India',
                'unit' => 'piece',
                'hs_code' => '8437.10.00',
                'images' => ['thresher1.jpg'],
                'specifications' => ['capacity' => '500 kg/h', 'power' => '10 HP', 'crops' => 'Multi-crop'],
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 14,
            ],
            // Food Products
            [
                'name' => 'Berbere Spice Mix',
                'slug' => 'berbere-spice-mix',
                'sku' => 'FOO-003',
                'description' => 'Traditional Ethiopian berbere spice blend for authentic cuisine.',
                'price' => 8.50,
                'cost' => 6.80,
                'quantity' => 1200,
                'category_id' => $foodCat->id ?? null,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '0904.11.00',
                'images' => ['berbere1.jpg'],
                'specifications' => ['type' => 'Berbere', 'packaging' => '1kg bags', 'shelf_life' => '24 months'],
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 15,
            ],
            [
                'name' => 'Shiro Powder',
                'slug' => 'shiro-powder',
                'sku' => 'FOO-004',
                'description' => 'Ground chickpea flour for traditional Ethiopian shiro wot.',
                'price' => 4.50,
                'cost' => 3.60,
                'quantity' => 1500,
                'category_id' => $foodCat->id ?? null,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '1106.20.00',
                'images' => ['shiro1.jpg'],
                'specifications' => ['type' => 'Chickpea Flour', 'packaging' => '500g bags', 'shelf_life' => '12 months'],
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 16,
            ],
            // Additional Textiles
            [
                'name' => 'Handwoven Ethiopian Scarf',
                'slug' => 'handwoven-ethiopian-scarf',
                'sku' => 'TEX-003',
                'description' => 'Traditional handwoven cotton scarf with Ethiopian patterns.',
                'price' => 25.00,
                'cost' => 18.00,
                'quantity' => 300,
                'category_id' => $textileCat->id ?? null,
                'origin_country' => 'Ethiopia',
                'unit' => 'piece',
                'hs_code' => '6214.30.00',
                'images' => ['scarf1.jpg', 'scarf2.jpg'],
                'specifications' => ['material' => '100% Cotton', 'size' => '180x70cm', 'style' => 'Traditional'],
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 17,
            ],
            [
                'name' => 'Ethiopian Cotton Yarn',
                'slug' => 'ethiopian-cotton-yarn',
                'sku' => 'TEX-004',
                'description' => 'High-quality cotton yarn for textile manufacturing.',
                'price' => 4.20,
                'cost' => 3.50,
                'quantity' => 4000,
                'category_id' => $textileCat->id ?? null,
                'origin_country' => 'Ethiopia',
                'unit' => 'kg',
                'hs_code' => '5205.11.00',
                'images' => ['yarn1.jpg'],
                'specifications' => ['material' => '100% Cotton', 'count' => '30/1', 'twist' => 'Z-twist'],
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 18,
            ],
            // Electronics
            [
                'name' => 'Smartphones Samsung Galaxy',
                'slug' => 'smartphones-samsung-galaxy',
                'sku' => 'ELE-003',
                'description' => 'Latest Samsung Galaxy smartphones for business and personal use.',
                'price' => 450.00,
                'cost' => 380.00,
                'quantity' => 80,
                'category_id' => $electronicsCat->id ?? null,
                'origin_country' => 'South Korea',
                'unit' => 'piece',
                'hs_code' => '8517.13.00',
                'images' => ['phone1.jpg', 'phone2.jpg'],
                'specifications' => ['brand' => 'Samsung', 'storage' => '128GB', 'ram' => '6GB'],
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 19,
            ],
            [
                'name' => 'LED TV 55 inch',
                'slug' => 'led-tv-55-inch',
                'sku' => 'ELE-004',
                'description' => 'High-definition 55-inch LED television with smart features.',
                'price' => 420.00,
                'cost' => 350.00,
                'quantity' => 40,
                'category_id' => $electronicsCat->id ?? null,
                'origin_country' => 'China',
                'unit' => 'piece',
                'hs_code' => '8528.72.00',
                'images' => ['tv1.jpg'],
                'specifications' => ['size' => '55 inches', 'resolution' => '4K UHD', 'smart' => 'Yes'],
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 20,
            ],
        ];

        foreach ($products as $product) {
            Product::updateOrCreate(['slug' => $product['slug']], $product);
        }
    }
}
